import 'package:flutter/material.dart';

/// A named group of icon keys, shown as a labelled section in the icon picker.
class IconGroup {
  final String label;
  final List<String> keys;
  const IconGroup(this.label, this.keys);
}

/// The full icon catalog, organised into themed groups. The original seed
/// keys (food/transport/…/investment) are kept so existing categories keep
/// resolving; the rest give users a broad library to build their own
/// categories and sub-categories from. All are built-in Material icons, so no
/// assets are bundled.
const List<IconGroup> iconGroups = [
  IconGroup('طعام وشراب', [
    'food',
    'fastfood',
    'local_cafe',
    'coffee',
    'local_bar',
    'local_pizza',
    'bakery_dining',
    'lunch_dining',
    'ramen_dining',
    'icecream',
    'cake',
    'egg',
    'set_meal',
    'liquor',
    'local_grocery_store',
  ]),
  IconGroup('تسوق', [
    'shopping',
    'shopping_cart',
    'shopping_basket',
    'checkroom',
    'local_mall',
    'storefront',
    'redeem',
    'diamond',
    'sell',
    'local_offer',
  ]),
  IconGroup('مواصلات', [
    'transport',
    'directions_car',
    'local_taxi',
    'train',
    'directions_subway',
    'flight',
    'two_wheeler',
    'moped',
    'local_gas_station',
    'electric_car',
    'pedal_bike',
    'directions_boat',
    'local_parking',
  ]),
  IconGroup('سكن وفواتير', [
    'home',
    'apartment',
    'bills',
    'bolt',
    'water_drop',
    'wifi',
    'phone_iphone',
    'cleaning_services',
    'chair',
    'bed',
    'kitchen',
    'roofing',
    'propane_tank',
  ]),
  IconGroup('صحة', [
    'health',
    'local_hospital',
    'medication',
    'healing',
    'fitness_center',
    'spa',
    'monitor_heart',
    'vaccines',
    'psychology',
    'visibility',
  ]),
  IconGroup('ترفيه', [
    'entertainment',
    'sports_esports',
    'music_note',
    'sports_soccer',
    'sports_basketball',
    'theaters',
    'casino',
    'park',
    'beach_access',
    'celebration',
    'pool',
    'hiking',
    'nightlife',
    'confirmation_number',
  ]),
  IconGroup('تعليم', [
    'school',
    'menu_book',
    'auto_stories',
    'science',
    'calculate',
    'laptop_chromebook',
    'edit',
    'backpack',
  ]),
  IconGroup('عمل ودخل', [
    'salary',
    'extra_income',
    'investment',
    'work',
    'business_center',
    'savings',
    'account_balance',
    'attach_money',
    'card_giftcard',
    'real_estate_agent',
  ]),
  IconGroup('عائلة وأطفال', [
    'child_care',
    'stroller',
    'toys',
    'pets',
    'family_restroom',
    'sports_handball',
    'cruelty_free',
  ]),
  IconGroup('تقنية', [
    'devices',
    'computer',
    'smartphone',
    'headphones',
    'camera_alt',
    'videogame_asset',
    'memory',
    'print',
    'router',
  ]),
  IconGroup('شخصي وخدمات', [
    'content_cut',
    'self_improvement',
    'local_laundry_service',
    'watch',
    'face',
    'volunteer_activism',
    'handshake',
    'security',
    'subscriptions',
  ]),
  IconGroup('عام', [
    'category',
    'other',
    'star',
    'favorite',
    'label',
    'bookmark',
    'flag',
    'lightbulb',
    'more_horiz',
  ]),
];

const Map<String, IconData> _icons = {
  // Original seed keys (kept stable).
  'food': Icons.restaurant,
  'transport': Icons.directions_bus,
  'shopping': Icons.shopping_bag,
  'bills': Icons.receipt_long,
  'health': Icons.medical_services,
  'entertainment': Icons.movie,
  'home': Icons.home,
  'other': Icons.category,
  'salary': Icons.payments,
  'extra_income': Icons.add_card,
  'investment': Icons.trending_up,
  // Food & drink
  'fastfood': Icons.fastfood,
  'local_cafe': Icons.local_cafe,
  'coffee': Icons.coffee,
  'local_bar': Icons.local_bar,
  'local_pizza': Icons.local_pizza,
  'bakery_dining': Icons.bakery_dining,
  'lunch_dining': Icons.lunch_dining,
  'ramen_dining': Icons.ramen_dining,
  'icecream': Icons.icecream,
  'cake': Icons.cake,
  'egg': Icons.egg,
  'set_meal': Icons.set_meal,
  'liquor': Icons.liquor,
  'local_grocery_store': Icons.local_grocery_store,
  // Shopping
  'shopping_cart': Icons.shopping_cart,
  'shopping_basket': Icons.shopping_basket,
  'checkroom': Icons.checkroom,
  'local_mall': Icons.local_mall,
  'storefront': Icons.storefront,
  'redeem': Icons.redeem,
  'diamond': Icons.diamond,
  'sell': Icons.sell,
  'local_offer': Icons.local_offer,
  // Transport
  'directions_car': Icons.directions_car,
  'local_taxi': Icons.local_taxi,
  'train': Icons.train,
  'directions_subway': Icons.directions_subway,
  'flight': Icons.flight,
  'two_wheeler': Icons.two_wheeler,
  'moped': Icons.moped,
  'local_gas_station': Icons.local_gas_station,
  'electric_car': Icons.electric_car,
  'pedal_bike': Icons.pedal_bike,
  'directions_boat': Icons.directions_boat,
  'local_parking': Icons.local_parking,
  // Home & bills
  'apartment': Icons.apartment,
  'bolt': Icons.bolt,
  'water_drop': Icons.water_drop,
  'wifi': Icons.wifi,
  'phone_iphone': Icons.phone_iphone,
  'cleaning_services': Icons.cleaning_services,
  'chair': Icons.chair,
  'bed': Icons.bed,
  'kitchen': Icons.kitchen,
  'roofing': Icons.roofing,
  'propane_tank': Icons.propane_tank,
  // Health
  'local_hospital': Icons.local_hospital,
  'medication': Icons.medication,
  'healing': Icons.healing,
  'fitness_center': Icons.fitness_center,
  'spa': Icons.spa,
  'monitor_heart': Icons.monitor_heart,
  'vaccines': Icons.vaccines,
  'psychology': Icons.psychology,
  'visibility': Icons.visibility,
  // Entertainment
  'sports_esports': Icons.sports_esports,
  'music_note': Icons.music_note,
  'sports_soccer': Icons.sports_soccer,
  'sports_basketball': Icons.sports_basketball,
  'theaters': Icons.theaters,
  'casino': Icons.casino,
  'park': Icons.park,
  'beach_access': Icons.beach_access,
  'celebration': Icons.celebration,
  'pool': Icons.pool,
  'hiking': Icons.hiking,
  'nightlife': Icons.nightlife,
  'confirmation_number': Icons.confirmation_number,
  // Education
  'school': Icons.school,
  'menu_book': Icons.menu_book,
  'auto_stories': Icons.auto_stories,
  'science': Icons.science,
  'calculate': Icons.calculate,
  'laptop_chromebook': Icons.laptop_chromebook,
  'edit': Icons.edit,
  'backpack': Icons.backpack,
  // Work & income
  'work': Icons.work,
  'business_center': Icons.business_center,
  'savings': Icons.savings,
  'account_balance': Icons.account_balance,
  'attach_money': Icons.attach_money,
  'card_giftcard': Icons.card_giftcard,
  'real_estate_agent': Icons.real_estate_agent,
  // Family & kids
  'child_care': Icons.child_care,
  'stroller': Icons.stroller,
  'toys': Icons.toys,
  'pets': Icons.pets,
  'family_restroom': Icons.family_restroom,
  'sports_handball': Icons.sports_handball,
  'cruelty_free': Icons.cruelty_free,
  // Tech
  'devices': Icons.devices,
  'computer': Icons.computer,
  'smartphone': Icons.smartphone,
  'headphones': Icons.headphones,
  'camera_alt': Icons.camera_alt,
  'videogame_asset': Icons.videogame_asset,
  'memory': Icons.memory,
  'print': Icons.print,
  'router': Icons.router,
  // Personal & services
  'content_cut': Icons.content_cut,
  'self_improvement': Icons.self_improvement,
  'local_laundry_service': Icons.local_laundry_service,
  'watch': Icons.watch,
  'face': Icons.face,
  'volunteer_activism': Icons.volunteer_activism,
  'handshake': Icons.handshake,
  'security': Icons.security,
  'subscriptions': Icons.subscriptions,
  // General
  'star': Icons.star,
  'favorite': Icons.favorite,
  'label': Icons.label,
  'bookmark': Icons.bookmark,
  'flag': Icons.flag,
  'lightbulb': Icons.lightbulb,
  'more_horiz': Icons.more_horiz,
};

IconData iconForKey(String key) => _icons[key] ?? Icons.category;

/// Flat list of every icon key, in group order. Used where a non-grouped
/// list is enough.
final List<String> availableIconKeys = [
  for (final group in iconGroups) ...group.keys,
];
